name: arb_translate
description: >-
  A command-line tool for automatically generating missing translations to ARB
  files using Google Gemini or OpenAI ChatGPT by LeanCode.
version: 1.3.0
repository: https://github.com/leancodepl/arb_translate
issue_tracker: https://github.com/leancodepl/arb_translate/issues
topics:
  - localization
  - l10n
  - arb
  - ai
  - gemini

executables:
  arb_translate:

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  dart_openai: ^5.1.0
  file: ^7.0.1
  google_generative_ai: ^0.4.6
  http: ^1.3.0
  intl: ^0.20.2
  meta: ^1.16.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
