name: arb_translate
description: >-
  A command-line tool for automatically generating missing translations to ARB
  files using Google Gemini or OpenAI ChatGPT by LeanCode.
version: 1.1.0
repository: https://github.com/leancodepl/arb_translate
issue_tracker: https://github.com/leancodepl/arb_translate/issues
topics:
  - localization
  - l10n
  - arb
  - ai
  - gemini

executables:
  arb_translate:

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  dart_openai: ^5.1.0
  file: ^7.0.0
  google_generative_ai: ^0.4.0
  http: ^1.2.0
  intl: ^0.19.0
  meta: ^1.14.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
